### ISSUE TITLE
SummaryModel requires access to internal notification APIs

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3662]
Tracks regression from https://github.com/mapbox/mapbox-navigation-android/pull/2531 which added dependency on the runtime trip notification module to the Nav UI SDK. When the notification is attempted to be replaced, it crashes with:
```
2020-10-19 09:15:20.026 32662-32662/com.example.navigaionui E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.navigaionui, PID: 32662
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/navigation/trip/notification/internal/TimeFormatter;
        at com.mapbox.navigation.ui.summary.SummaryModel.create(SummaryModel.java:36)
        at com.mapbox.navigation.ui.summary.SummaryBottomSheet.update(SummaryBottomSheet.java:152)
        at com.mapbox.navigation.ui.summary.-$$Lambda$OhVP-l4_iDAzOOGkovpQkcrQp-c.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.mapbox.navigation.ui.NavigationViewModel.updateRouteProgress(NavigationViewModel.java:239)
        at com.mapbox.navigation.ui.NavigationViewModelProgressObserver.onRouteProgressChanged(NavigationViewModelProgressObserver.java:35)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:482)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:49)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:457)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.navigation.trip.notification.internal.TimeFormatter" on path: DexPathList[[zip file "/data/app/com.example.navigaionui-HA3KJDqh7JE9gMpPU-uoAA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.navigaionui-HA3KJDqh7JE9gMpPU-uoAA==/lib/x86, /data/app/com.example.navigaionui-HA3KJDqh7JE9gMpPU-uoAA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mapbox.navigation.ui.summary.SummaryModel.create(SummaryModel.java:36) 
        at com.mapbox.navigation.ui.summary.SummaryBottomSheet.update(SummaryBottomSheet.java:152) 
        at com.mapbox.navigation.ui.summary.-$$Lambda$OhVP-l4_iDAzOOGkovpQkcrQp-c.onChanged(Unknown Source:4) 
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131) 
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149) 
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307) 
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
        at com.mapbox.navigation.ui.NavigationViewModel.updateRouteProgress(NavigationViewModel.java:239) 
        at com.mapbox.navigation.ui.NavigationViewModelProgressObserver.onRouteProgressChanged(NavigationViewModelProgressObserver.java:35) 
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:482) 
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:49) 
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:457) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

This is due to this dependency:
https://github.com/mapbox/mapbox-navigation-android/blob/a3dfcaa1622de207bb8a09e310f86a384c3af024/libnavigation-ui/build.gradle#L68
and this requirement:
https://github.com/mapbox/mapbox-navigation-android/blob/a3dfcaa1622de207bb8a09e310f86a384c3af024/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryModel.java#L13

No SDK component should ever depend on the implementation of a module directly. They can only use the interfaces from the `base` module.

/cc @mapbox/navigation-android
